<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>ThinkBloke</title>
        <script src="../../js/show.js" type="text/javascript"></script>
        <script src="../../js/scroll.js" type="text/javascript"></script>      
        <script src="../../js/jquery.js"></script>        
        <script src="https://gitcdn.github.io/bootstrap-toggle/2.2.0/js/bootstrap-toggle.min.js"></script>      
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7/jquery.js"></script>     
        <!-- Bootstrap -->
        <link href="css/main.css" rel="stylesheet" type="text/css"/>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
        <link href="../../css/social-buttons.css" rel="stylesheet">
        <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
        <link href="https://gitcdn.github.io/bootstrap-toggle/2.2.0/css/bootstrap-toggle.min.css" rel="stylesheet">
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
        <script src="http://code.jquery.com/jquery-1.9.1.js"></script>

    </head>
    <body>  
        <!-- Register Tab -->
        <div class="modal fade bs-example-modal-md" id="register" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog modal-md">
                <div class="modal-content" style="padding: 10px;">
                    <form class="form-horizontal" role="form" data-toggle="validator" action="index.php" method="post">
                        <fieldset>
                            <!-- Form Name -->
                            <legend>Create an Account</legend>
                            <!-- Text input-->
                            <div class="form-group" style="padding: 5px;">
                                <label class="col-md-4 control-label" for="EmailAddress">Email Address</label>  
                                <div class="col-md-6">
                                    <input id="EmailAddress" name="email" class="form-control input-md" required="" type="email"  data-error="Invalid Email Address">
                                    <div class="help-block with-errors"></div>
                                </div>
                            </div>

                            <!-- Text input-->
                            <div class="form-group" style="padding: 5px;">
                                <label class="col-md-4 control-label" for="RegUsername">Username</label>  
                                <div class="col-md-6">
                                    <input id="RegUsername" name="RegUsername" class="form-control input-md" required="" type="text">                        
                                </div>
                            </div>

                            <!-- Password input-->
                            <div class="form-group" style="padding: 5px;">
                                <label class="col-md-4 control-label" for="FirstPassword">Password</label>
                                <div class="col-md-6">
                                    <input id="FirstPassword" name="firstpass" data-minlength="6" class="form-control input-md" required="" type="password">


                                </div>
                            </div>

                            <!-- Password input-->
                            <div class="form-group" style="padding: 5px;">
                                <label class="col-md-4 control-label" for="ConfirmPassword">Confirm Password</label>
                                <div class="col-md-6">
                                    <input id="ConfirmPassword" data-match="#FirstPassword" data-match-error="Passwords don't match" name="ConPassword" class="form-control input-md" data-minlength="6" required="" type="password">
                                    <div class="help-block with-errors"></div>                                
                                </div>
                            </div>

                            <!-- Button -->
                            <div class="form-group">
                                <label class="col-md-4 control-label" for="createBtn"></label>
                                <div class="col-md-4">
                                    <button id="createBtn" type="submit" name="submitR" value="submitR" class="btn btn-success">Register</button>
                                </div>
                            </div>

                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
        <!-- Login Tab -->
        <div class="modal fade bs-example-modal-md" id="login" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog modal-md">
                <div class="modal-content" style="padding: 15px;">
                    <form class="form-horizontal" action="index.php" data-toggle="validator" role="form" method="post">
                        <fieldset>

                            <!-- Form Name -->
                            <legend>Login</legend>

                            <!-- Text input-->

                            <div class="form-group" style="padding: 5px;">
                                <label class="col-md-4 control-label" for="username">Username</label>  
                                <div class="col-md-6">
                                    <input id="username" name="username" type="text" class="form-control input-md" required="">

                                </div>
                            </div>



                            <!-- Password input-->
                            <div class="form-group" style="padding: 5px;">
                                <label class="col-md-4 control-label" for="Password">Password</label>
                                <div class="col-md-6">
                                    <input id="Password" name="password" placeholder="" class="form-control input-md" required="" type="password">


                                </div>
                            </div>

                            <!-- Button -->
                            <div class="form-group">
                                <label class="col-md-4 control-label" for="submitL"></label>
                                <div class="col-md-4">
                                    <button id="submitL" type="submit" name="submitL" value="submitL" class="btn btn-success">Login</button>
                                </div>
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
        <!-- NAVBAR STARTS HERE -->
        <nav class="navbar navbar-default"  role="navigation">
            <div class="container-fluid" >
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-megadropdown-tabs-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" id="navLogo" href="index.php"><img alt="logo" src="images/logo.png"></a>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-megadropdown-tabs-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                       	<li class="dropdown mega-dropdown hidden-xs">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Categories <span class="caret"></span></a>
                            <div class="dropdown-menu mega-dropdown-menu">
                                <div class="row-centered">
                                    <div class="container-fluid">
                                        <!-- Tab panes -->
                                        <div class="tab-content">
                                            <div class="tab-pane active">
                                                <ul class="nav-list list-inline">
                                                    <li><a href="?Gaming"><img alt="gaming" src="../../images/gaming.png"><span>Gaming</span></a></li>                                
                                                    <li><a href="?Entertainment"><img alt="entertainment" src="../../images/entertainment.png"><span>Entertainment</span></a></li>
                                                    <li><a href="?Sports"><img alt="sports" src="../../images/sports.png"><span>Sports & Exercise</span></a></li>
                                                    <li><a href="?Gadgets"><img alt="gadgets" src="../../images/gadgets.png"><span>Gadgets</span></a></li>
                                                    <li><a href="?Novelty"><img alt="novelty" src="../../images/novelty.png"><span>Novelty</span></a></li>
                                                    <li><a href="?Food&AMP;Drink"><img alt="foodndrink" src="../../images/foodndrink.png"><span>Food & Drink</span></a></li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- Nav tabs -->
                                </div>
                            </div>				
                        </li>
                        <?php
                        if (isset($_COOKIE['username']) && $_COOKIE['username'] == 'admin' or isset($_COOKIE['username']) && $_COOKIE['username'] == 'ste' or isset($_COOKIE['username']) && $_COOKIE['username'] == 'charlie') {
                            echo '<li><a href="add.php">Administrator Settings</a></li>';
                        }
                        ?>  

                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <?php
                        if (!isset($_COOKIE['username'])) {

                            echo ' <li style="display:inline;"><button style="margin:7px;" data-target="#register" data-toggle="modal" class="btn btn-default">Create an Account</button></li>
                                    <li style="margin-top: 7px;"><button data-toggle="modal" data-target="#login" class="btn btn-default">Login</button></li>';
                        } else {
                            echo "<a href='profile.php'><button id='button' class='btn btn-default'>Profile</button></a>
                                <a href='logout.php'><button id='button' class='btn btn-default'>Logout</button></a>"
                            . "";
                        }
                        ?>                 
                    </ul>
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>
        <!-- NAVBAR FINISHES HERE -->
        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
        <!-- Include all compiled plugins (below), or include individual files as needed -->
        <script src="js/bootstrap.min.js"></script>    
        <script src="../../js/validator.js" type="text/javascript"></script>
        <!-- If homepage, display header, if profile page, display profile picture -->
        <?php
        if ($_SERVER['PHP_SELF'] == '/profile.php') {
            foreach ($view->userDataSet as $userData) {
                echo '<div class="panel panel-default" id="pp"><div class="panel-body"><img src="../../images/' . $userData->getProfilePicture() . '" alt="Profile Picture" height="130" width="130"></div></div>';
            }
        } else {
            echo '<div id="head"><a href="index.php"><img alt="header" src="../images/header.png" class="img img-responsive"></a></div>';
        }
        ?>
       